### PR TITLE
WIP: Example of using Conda with conda-forge-provided dependencies

### PR DESCRIPTION
**Pull request by traversaro**
Hi @patricia-gallardo, thanks for the nice initiative of comparisong of C++ dependency providers. I wanted to contribute an example of using [Conda](https://docs.conda.io) with [conda-forge](https://conda-forge.org/)-provided dependencies, that we (I work in research, see https://www.iit.it/web/ami/home) use in C++-based environments (for a longer discussion see https://arxiv.org/abs/2104.12910). 

However, while preparing the example I noticed a problem in the sfml package of conda-forge. I reported it in , but it could take some time to solve it, so in the meanwhile I opened the PR as WIP, as anyhow Windows and macOS are working fine and the basic structure is there, even if it it could be improved in many ways.

fyi @wolfv @Tobias-Fischer

### CODE REVIEW

**Comment by traversaro** [comment]
Upstream sfml conda-forge packaging issue: https://github.com/conda-forge/sfml-feedstock/issues/4 .

**Comment by patricia-gallardo** [comment]
This is awesome, thank you 🙏

**Comment by patricia-gallardo** [comment]
I'm merging it, all of them has issues, this is very similar to Conans, the rest of them are grabbing things off the system :)

Thank you!

**Comment by patricia-gallardo** [comment]
I will need to make some changes since it doesn't work when included in the root project because it isn't completely CMake driven. Can I invoke it from CMake? Do you know of an example of how that is done?

**Comment by patricia-gallardo** [comment]
I understand, unfortunately that was specifically the usecase I was looking for here. I do like the cross platform bit though, it makes it very similar to Conan and Vcpkg. All it seems to be missing is the CMake invocation which is supported by the others.

**Comment by traversaro** [comment]
Ack, I see. I guess that if someone is interested can provide the missing bits, otherwise you can just remove the conda part.

**Pull request merged**
